### ISSUE TITLE
Status 400 on CORS preflight request for multipart initiate

### ISSUE THREAD

**Issue by laterne** [exoscale/pithos#105]
I'm trying to initiate a multipart upload using CORS. The CORS configuration seems to be working, but I receive a 400 Bad Request error during the preflight request.

preflight request with curl for POST "https\://sos.exo.io/mybucket/myobject?uploads": [curl.txt](https://github.com/exoscale/pithos/files/373872/curl.txt)

the preflight for PUT https\://sos.exo.io/mybucket/myobject works

Am I missing something?

**Comment by pozylon** [comment]
see https://github.com/exoscale/pithos/issues/52
