### ISSUE TITLE
Connecting with AWS Java SDK

### ISSUE THREAD

**Issue by vromero** [exoscale/pithos#113]
Does anyone have been able to connect to pithos with Amazon AWS Java SDK?
If so, is there any example out there?

**Comment by llambiel** [comment]
Sure, this should do the trick: https://gist.github.com/pyr/833c87a391f176e507b0

**Comment by vromero** [comment]
Excellent, thanks!
I am guessing the endpoint value is not actually relevant, isn't it?

**Comment by llambiel** [comment]
This one is for the Exoscale Object store. Of course it depends on your setup. It's recommended to have a resolvable name here. It should probably work with a value like localhost for testing, but I think we've never tried that with the AWS SDK.

**Comment by sandeepsdixit** [comment]
@llambiel The link you have provided returns 404. Can you please explain how to configure with AWS Java SDK? Below is my junit:

`	public void testPithosIO() {
		try {
			ClientConfiguration config = new ClientConfiguration();
			config.setSignerOverride("S3SignerType");
			
			EndpointConfiguration endpointConfiguration = new EndpointConfiguration("http://testmbr1.kabuter.com:8081",
					"myregion");
			BasicAWSCredentials awsCreds = new BasicAWSCredentials("AKIAIOSFODNN7EXAMPLE",
					"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY");
			AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
					.withRegion("myregion")
					.withClientConfiguration(config)
					.withCredentials(new AWSStaticCredentialsProvider(awsCreds))
					.withEndpointConfiguration(endpointConfiguration).build();
			s3Client.createBucket("mybucket1");
			System.out.println(s3Client.listBuckets());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
`

It however fails with:
`com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to mybucket1.testmbr1.kabuter.com:8081 [mybucket1.testmbr1.kabuter.com/198.105.254.130, mybucket1.testmbr1.kabuter.com/104.239.207.44] failed: connect timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1069)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
`
