### ISSUE TITLE
Setting a canned ACL on an object does not give the owner full control on it

### ISSUE THREAD

**Issue by GaretJax** [exoscale/pithos#121]
When setting a canned ACL (e.g. 'public-read'), the creating user does not get access to the object.

Example with boto3:
```
bucket.put_object(Body='body', Key='test1', ACL='private')
bucket.Object('test1').get()  # Works

bucket.put_object(Body='body', Key='test2', ACL='public-read')
bucket.Object('test2').get()  # AccessDenied
```

Note that in the second case, the ACL is `public-read` (which is set correctly and works for anonymous users), but it still fails for the authenticated user.

This is the result in the Exoscale console:
![image](https://cloud.githubusercontent.com/assets/86236/19594054/b330baf4-9783-11e6-9595-5f2326f66d37.png)

![image](https://cloud.githubusercontent.com/assets/86236/19594049/ac41d976-9783-11e6-96ff-80da60621a41.png)

**Comment by GaretJax** [comment]
Might be worth to say that the user doing these operations is not the one which created the bucket, but has FULL_CONTROL over the bucket (which would imply that he can do everything with the objects contained therein).

**Comment by brutasse** [comment]
Hey @GaretJax, thanks for the report! I identified the issue and submitted #123. We'll deploy a fix asap.

**Comment by GaretJax** [comment]
Cool, looking forward to be able to test it.
