### ISSUE TITLE
quotas?

### ISSUE THREAD

**Issue by InformatiQ** [exoscale/pithos#122]
I can see that here is no way to set quota limit on pithos.
Is there a way to do any sort of accounting as in to figure out tje size of files uploaded by an account ?

**Comment by pyr** [comment]
@InformatiQ You can rely on the reporter to watch for account consumption. In most cases, you'll want a reporter that does something else than logging and provide your own implementation.

**Comment by pyr** [comment]
Here is some documentation on the interface: http://pithos.io/developer.html#reporter

**Comment by InformatiQ** [comment]
thanks
