### ISSUE TITLE
Authenticated Requests Begin failing

### ISSUE THREAD

**Issue by siosphere** [exoscale/pithos#128]
After placing a document into the store, the first few authenticated requests are successful, but after a while they begin failing with:

No implementation of method: :gen-event of protocol: #'clojure.data.xml/EventGeneration found for class: org.joda.time.DateTime

I haven't been able to get a 100% reproducable case yet

**Comment by pyr** [comment]
Hi!

I would need the method used for retrieving the object and a full log of both the HTTP transmission as well as the server logs to investigate further.

**Comment by pyr** [comment]
My hunch is that you are hitting a signature error, but are running on the latest release which has a formatting error for the expiry field, fixed in https://github.com/exoscale/pithos/commit/c832dcb96817801b6c235cffe34b6409368000ba
