### ISSUE TITLE
Authentication issue with docker register

### ISSUE THREAD

**Issue by pegerto** [exoscale/pithos#132]
Hi, 

I test my installation from boto and it work perfectly but the signature for the docker register fail with a NullPointer exception

```
pithos_1     | INFO [2016-11-08 18:20:49,023] qtp1853364091-50 - io.pithos.operations executing request #uuid "6787c762-8615-41fd-bcac-8aafb16553ca" : put-bucket on s3://docker
pithos_1     | INFO [2016-11-08 18:21:23,757] qtp1853364091-46 - io.pithos.sig will throw because of failed signature!
pithos_1     | DEBUG [2016-11-08 18:21:23,761] qtp1853364091-46 - io.pithos.sig got exception during signing
pithos_1     | java.lang.NullPointerException: null
pithos_1     | 	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:301) ~[pithos.jar:na]
pithos_1     | 	at io.pithos.sig$sign_string.invokeStatic(sig.clj:42) ~[pithos.jar:na]
pithos_1     | 	at io.pithos.sig$sign_string.invoke(sig.clj:40) ~[pithos.jar:na]
pithos_1     | 	at io.pithos.sig$sign_request.invokeStatic(sig.clj:50) ~[pithos.jar:na]
pithos_1     | 	at io.pithos.sig$sign_request.invoke(sig.clj:47) ~[pithos.jar:na]
pithos_1     | 	at io.pithos.sig$validate$fn__1476.invoke(sig.clj:94) ~[pithos.jar:na]
pithos_1     | 	at io.pithos.sig$validate.invokeStatic(sig.clj:94) [pithos.jar:na]
pithos_1     | 	at io.pithos.sig$validate.invoke(sig.clj:87) [pithos.jar:na]
pithos_1     | 	at io.pithos.request$authenticate.invokeStatic(request.clj:225) [pithos.jar:na]
pithos_1     | 	at io.pithos.request$authenticate.invoke(request.clj:203) [pithos.jar:na]
pithos_1     | 	at io.pithos.request$prepare.invokeStatic(request.clj:263) [pithos.jar:na]
pithos_1     | 	at io.pithos.request$prepare.invoke(request.clj:245) [pithos.jar:na]
pithos_1     | 	at io.pithos.request$safe_prepare.invokeStatic(request.clj:269) [pithos.jar:na]
pithos_1     | 	at io.pithos.request$safe_prepare.invoke(request.clj:266) [pithos.jar:na]
pithos_1     | 	at io.pithos.api$executor$fn__13348.invoke(api.clj:20) [pithos.jar:na]
```

My version is build from head as I had the same issue with 0.7.5. 

The configuration of the registry is to dissable v4 but I can see the request in v4

```
Credential=AKIAIOSFODNN7EXAMPLE/20161108/myregion/s3/aws4_request, 
```
Do we have any plan for support signature version 4?

Thanks

**Comment by brutasse** [comment]
Hi,

There are currently several issues with the registry:

- v2 signing is not in a released version of docker distribution
- v2 implementation needs a patch to work correctly: https://github.com/docker/distribution/pull/2036/files
- Pithos needs a couple of adjustments which are being implemented in #131 
- There could be more issues related to AWS S3 API coverage but we're getting there.

It should be possible to run the registry with Pithos rather soon but at the moment it's a bit tedious.

**Comment by pegerto** [comment]
Hi @brutasse 

Complete agree the problem with aws-s3, in general we try to explore multiple HA solution so we have a limited effort to solve the issues.

For a quick solution we move to the amz driver

```
storage:
  s3goamz:
    accesskey: ""
    secretkey: ""
```

This driver do not support on-prem endpoints, but the change is relative simple 
https://github.com/pegerto/distribution/commit/4f37614e7d544a24b462c7f9d810d1326ad971ac

We are testing the registry without major issues, but I will keep you updated.

Regards.

**Comment by brutasse** [comment]
Hi @pegerto,

Note that goamz is deprecated and will be removed in the near(ish) future.

We're working on making the registry compatible with Pithos in v2 signing mode.

**Comment by pegerto** [comment]
Hi @brutasse 

I know the plans to deprecate the driver, now that pyr:fix/sort-v2-headers 11 hours ago  is merged, I am happy to test the new driver

**Comment by brutasse** [comment]
@pegerto there's an additional patch that needs to be submitted to docker/distribution, I'm working on it. Should be ready soon.

**Comment by brutasse** [comment]
@pegerto patch is ready. Docker distribution works properly with the patch at https://github.com/docker/distribution/pull/2069 and the following configuration:

```yaml
storage:
  s3:
    regionendpoint: host.domain
    accesskey: <your key>
    secretkey: <your secret>
    v4auth: false
    bucket: <bucket-name>
    encrypt: false
    multipartcopythresholdsize: 5368709120
```

There's still an issue with multipart copy during uploads, but it seems to be a limitation in the golang aws sdk. Raising the limit to 5GB disables multipart and blobs are pushed correctly.

I'll go ahead and close the issue as this is already a good solution to have a working docker registry with Pithos.
