### ISSUE TITLE
write consistency

### ISSUE THREAD

**Issue by InformatiQ** [exoscale/pithos#140]
```
wrcty   (or (some-> write-consistency keyword) :quorum)
```
can i just define write-consistency: 'LOCAL_QUORUM' or is it different?

**Comment by brutasse** [comment]
This is passed to Alia's `execute` function. Possible values are listed at https://mpenet.github.io/alia/qbits.alia.html#var-execute

For local quorum, that would be '`local-quorum`'

**Comment by InformatiQ** [comment]
thanks
