### ISSUE TITLE
log to syslog

### ISSUE THREAD

**Issue by InformatiQ** [exoscale/pithos#143]
in the docs ity mentions to set external=true to bypas sthe logging conf and provide a log4j.properties while on master it talks about logback.xml
I tried with ways and it does not pick up the file
i used java -Dlogback.configurationFile="/home/rhanna/logback.xml"  -jar pithos-0... and java -Dlog4j.configurationFile="/home/rhanna/log4j.properties"  -jar pithos-....

what am i doing wrong?
 I also tried passing in the yaml
```
logging:
  appenders:
    - { host: '127.0.0.1', port: 514, appender: 'syslog', encoder: "%p [%d] %t - %c - %m%n"}
```

**Comment by InformatiQ** [comment]
ping

**Comment by InformatiQ** [comment]
using the latest from master branch with the bumped unilog, logging to syslog only works if the file in resorces dir. but it only logs io.netty.util.internal.PlatformDependent logs no pithos logs

**Comment by pyr** [comment]
Hi @InformatiQ,

Thanks for the heads-up, i'll try to build a reproducing case and get back to you.

**Comment by pyr** [comment]
Ah, I see that you are trying to use a `log4j.properties` file, you are now expected to provide a logback configuration file, as this is what `unilog` relies on.

**Comment by InformatiQ** [comment]
when using logback and removing the log4j configs i stiil only see logs of io.netty.util.internal.PlatformDependent  and no pithos logs
