### ISSUE TITLE
HEAD Object Requests Fail to Properly Validate Signature

### ISSUE THREAD

**Issue by phene** [exoscale/pithos#144]
I've been debugging an issue and discovered that HEAD requests consistently fail with a 403 response from pithos.

```
$ s3cmd get s3://us-cap-prot2/attachments/22/heic1402a.jpg
download: 's3://us-cap-prot2/attachments/22/heic1402a.jpg' -> './heic1402a.jpg'  [1 of 1]
 725101 of 725101   100% in    0s    40.43 MB/s  done

$ s3cmd info s3://us-cap-prot2/attachments/22/heic1402a.jpg
ERROR: S3 error: 403 (Forbidden)
```

Both s3cmd and the aws-sdk-v1 ruby library both produce Authorization headers for the HEAD request, which appears pithos does not accept. From my reading of the code, it appears there are no tests in this repository for HEAD requests and the validation of the Authorization header.

Nginx proxy log with Authorization header included:
```
# Ruby
[elided] - - [21/Dec/2016:21:44:40 +0000] TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "HEAD /us-cap-prot2/tenants/1/attachments/22/heic1402a.jpg HTTP/1.1" 403  0 "-" "aws-sdk-ruby/1.66.0 ruby/2.2.4 x86_64-linux" "-" [elided] [elided ip]:8098 0.004 AWS _eqZm-vT6G2XFMWSWGegeA:LHSIFlVHVyxUyLN/h+xxC9HlfXs=

# s3cmd
[elided] - - [21/Dec/2016:21:44:43 +0000] TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "HEAD /us-cap-prot2/tenants/1/attachments/22/heic1402a.jpg HTTP/1.1" 403  0 "-" "-" "-" [elided] [elided ip]:8098 0.005 AWS _eqZm-vT6G2XFMWSWGegeA:b/VnSDA5O5p62N4Esv7HIWqWlTY=
```

Pithos log for the 2 requests:

```
INFO [2016-12-21 21:44:40,719] qtp1119158442-51 - io.pithos.sig will throw because of failed signature!
INFO [2016-12-21 21:44:43,391] qtp1119158442-53 - io.pithos.sig will throw because of failed signature!
```

**Comment by brutasse** [comment]
Can you share the output of the same s3cmd call the `--debug` command-line flag? We can see the full HTTP requests and responses this way.

It's probably a setup issue because `s3cmd info` works fine on Exoscale.

**Comment by phene** [comment]
All other s3cmd invocations (get, put, sync, mb, ls, rm, delete) work with the present configuration. Here's the request from the debug output:

```
DEBUG: Sending request method_string='HEAD', uri='/us-cap-prot2/tenants/1/attachments/22/heic1402a.jpg', headers={'Authorization': 'AWS _eqZm-vT6G2XFMWSWGegeA:aTjtbnbIcs0nyWeCuvXNIpgZljw=', 'x-amz-date': 'Thu, 22 Dec 2016 16:52:40 +0000'}, body=(0 bytes)
DEBUG: Response: {'status': 403, 'headers': {'date': 'Thu, 22 Dec 2016 16:52:40 GMT', 'x-amz-id-2': '281d1c7c-cc5f-4220-924c-9d15b876e807', 'connection': 'keep-alive', 'x-amz-request-id': '281d1c7c-cc5f-4220-924c-9d15b876e807', 'content-type': 'application/xml'}, 'reason': 'Forbidden', 'data': ''}
```

**Comment by brutasse** [comment]
Ah, the body is empty because it's a HEAD request.

Can you show the lines that start with

```
DEBUG: Using signature v2
DEBUG: SignHeaders: …
```

What's the vaule of `host_base` and `host_bucket` in your config?

**Comment by phene** [comment]
```
DEBUG: String 'tenants/1/attachments/22/heic1402a.jpg' encoded to 'tenants/1/attachments/22/heic1402a.jpg'
DEBUG: CreateRequest: resource[uri]=/tenants/1/attachments/22/heic1402a.jpg
DEBUG: Using signature v2
DEBUG: SignHeaders: 'HEAD\n\n\n\nx-amz-date:Thu, 22 Dec 2016 16:52:40 +0000\n/us-cap-prot2/tenants/1/attachments/22/heic1402a.jpg'
```

I'd rather not share the hostname, but the `host_base` and `host_bucket` are the same value. `bucket_location = us-cap-prot2`, though.

**Comment by phene** [comment]
After pointing s3cmd directly at pithos, I was able to get a successful info request, so the problem is probably in my nginx configuration. Closing the ticket.

**Comment by phene** [comment]
Just for additional edification, it appears that my older version of nginx is missing the `proxy_cache_convert_head` directive introduced in 1.9.7, which is causing pithos to receive the wrong request method when caching is enabled.
