### ISSUE TITLE
Support for expiration rules

### ISSUE THREAD

**Issue by vincentbernat** [exoscale/pithos#148]
Hey!

S3 allows one to attach expiration rules to buckets. Would be great if Pithos supported that. See http://docs.aws.amazon.com/AmazonS3/latest/dev/intro-lifecycle-rules.html#intro-lifecycle-rules-actions.

**Comment by pyr** [comment]
Pithos is currently not designed to support lifecycles as it would require building an executor framework for tasks. This might come in follow-up major releases but not expected at the moment.
