### ISSUE TITLE
lein fatrpm fails

### ISSUE THREAD

**Issue by elnygren** [exoscale/pithos#150]
running `lein fatrpm` (after having `lein run` fetch all the dependencies) fails:

```
clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: org.codehaus.mojo.rpm.RPMMojo, compiling:(leiningen/fatrpm.clj:1:1)
```

and

```
Caused by: java.lang.ClassNotFoundException: org.codehaus.mojo.rpm.RPMMojo
```

---

I'm trying to get a .deb from the newest master since quite a bit of time has passed from last release.

EDIT: `lein uberjar` does work and looks like you've bumped to 0.7.6. Perhaps we could have a .deb and release at github too? :)

**Comment by pyr** [comment]
we will create a release shortly, indeed.
