### ISSUE TITLE
Can I have multiple pithos.io services?

### ISSUE THREAD

**Issue by sandeepsdixit** [exoscale/pithos#158]
In my test environment I have a C* cluster of 3 nodes. To eliminate SPOF, can I run 
`java -jar pithos-quickstart-VERSION-standalone.jar -f pithos.yaml`
on all 3 nodes? pithos.yaml will be identical except the service-uri - which will be the uri of the node its running on. 

Is this a right strategy/approach?

**Comment by brutasse** [comment]
The way to go would be to run pithos on all 3 nodes, with the **same** service-uri and a HA load balancer in front to split traffic across your 3 nodes.

Different service-uris would mean your clients need to be aware of cluster topology.

**Comment by sandeepsdixit** [comment]
Got it - I will configure accordingly. However if I were to use different uris will that create any kind of concurrency issues? My assumption is since its delegating everything to C* cluster there should not be - unless there are any server-uri specific configuration/state maintained by pithos.

**Comment by sandeepsdixit** [comment]
Also I noticed that pithos is taking about 10-12% memory (out of 4GB). Is it normal? Is it mainly because of the embedded Jetty? Can I run pithos in wildfly?
