### ISSUE TITLE
AWS SDK C# SignatureDoesNotMatch on some bucket names

### ISSUE THREAD

**Issue by mark-draper** [exoscale/pithos#163]
I'm seeing some very strange behaviour using the AWS SDK for .NET C# and I'm stumped.

I can connect and list buckets fine, but when I try to create or query buckets, it doesn't always work. Sometimes (it seems related to the bucket name) DoesS3BucketExist(bucketName) will return true even when ListBuckets() returns an empty list. If I attempt GetBucketLocation() using this bucketName, a SignatureDoesNotMatch exception is thrown. For other bucket names, DoesS3BucketExist correctly returns false and I can succesfully PutBucket() and then when I inspect the Cassandra database I see the entry in the storage.buckets table. GetBucketLocation() will return the region that I see in the table.

It all seems very strange!

When I try "my-test-bucket" as a bucket name, DoesS3BucketExist will return true even when ListBuckets returns an empty list. When I try "my-test-Bucket" (note the upper-case "B") it works fine. I have not yet tried to upload and object using this bucket yet, though.

Here are excerpts from the pithos logs where things start to diverge:

```
"my-test-Bucket":
DEBUG [2017-12-14 21:24:08,585] qtp1140430871-52 - org.eclipse.jetty.http.HttpParser parseNext s=START HeapByteBuffer@10458dac[p=0,l=178,c=65536,r=178]={<<<HEAD http://s3.am...azonaws.com\r\n\r\n>>>rvice_Pack_1 Clie...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
DEBUG [2017-12-14 21:24:08,585] qtp1140430871-52 - org.eclipse.jetty.http.HttpParser START --> SPACE1
DEBUG [2017-12-14 21:24:08,585] qtp1140430871-52 - org.eclipse.jetty.http.HttpParser SPACE1 --> URI
DEBUG [2017-12-14 21:24:08,585] qtp1140430871-52 - org.eclipse.jetty.http.HttpParser URI --> SPACE2
DEBUG [2017-12-14 21:24:08,585] qtp1140430871-52 - org.eclipse.jetty.http.HttpParser SPACE2 --> REQUEST_VERSION
DEBUG [2017-12-14 21:24:08,585] qtp1140430871-52 - org.eclipse.jetty.http.HttpParser REQUEST_VERSION --> HEADER
DEBUG [2017-12-14 21:24:08,586] qtp1140430871-52 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_IN_VALUE
DEBUG [2017-12-14 21:24:08,586] qtp1140430871-52 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2017-12-14 21:24:08,586] qtp1140430871-52 - org.eclipse.jetty.http.HttpParser HEADER --> END
DEBUG [2017-12-14 21:24:08,586] qtp1140430871-52 - org.eclipse.jetty.server.HttpChannel HttpChannelOverHttp@595db7d0{r=2,c=false,a=IDLE,uri=-} messageComplete
DEBUG [2017-12-14 21:24:08,586] qtp1140430871-52 - org.eclipse.jetty.server.HttpInput HttpInputOverHTTP@7ca24061 EOF
DEBUG [2017-12-14 21:24:08,586] qtp1140430871-52 - org.eclipse.jetty.server.HttpChannel HttpChannelOverHttp@595db7d0{r=2,c=false,a=IDLE,uri=-} handle enter
DEBUG [2017-12-14 21:24:08,586] qtp1140430871-52 - http://s3.amazonaws.com/my-test-Bucket?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1513391049&Signature=qApqxyEMa%2FzMQ3PcNDcCxwgdmLw%3D - org.eclipse.jetty.server.HttpChannelState HttpChannelState@cd57896{s=IDLE i=true a=null} handling IDLE
DEBUG [2017-12-14 21:24:08,586] qtp1140430871-52 - http://s3.amazonaws.com/my-test-Bucket?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1513391049&Signature=qApqxyEMa%2FzMQ3PcNDcCxwgdmLw%3D - org.eclipse.jetty.server.HttpChannel HttpChannelOverHttp@595db7d0{r=2,c=false,a=DISPATCHED,uri=/my-test-Bucket} action REQUEST_DISPATCH
DEBUG [2017-12-14 21:24:08,586] qtp1140430871-52 - http://s3.amazonaws.com/my-test-Bucket?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1513391049&Signature=qApqxyEMa%2FzMQ3PcNDcCxwgdmLw%3D - org.eclipse.jetty.server.Server REQUEST HEAD /my-test-Bucket on HttpChannelOverHttp@595db7d0{r=2,c=false,a=DISPATCHED,uri=/my-test-Bucket}
DEBUG [2017-12-14 21:24:08,602] qtp1140430871-52 - http://s3.amazonaws.com/my-test-Bucket?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1513391049&Signature=qApqxyEMa%2FzMQ3PcNDcCxwgdmLw%3D - io.pithos.operations handling operation:  :head-bucket
```

```
"my-test-bucket":
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser parseNext s=START HeapByteBuffer@7ca0bd9e[p=0,l=196,c=65536,r=196]={<<<HEAD http://my-te...azonaws.com\r\n\r\n>>>tSync\r\nX-Amz-Date...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser START --> SPACE1
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser SPACE1 --> URI
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser URI --> SPACE2
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser SPACE2 --> REQUEST_VERSION
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser REQUEST_VERSION --> HEADER
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_VALUE
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser HEADER_VALUE --> HEADER_IN_VALUE
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.http.HttpParser HEADER --> END
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.server.HttpChannel HttpChannelOverHttp@274fe449{r=2,c=false,a=IDLE,uri=-} messageComplete
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.server.HttpInput HttpInputOverHTTP@2732e8fa EOF
DEBUG [2017-12-14 21:27:04,769] qtp1140430871-53 - org.eclipse.jetty.server.HttpChannel HttpChannelOverHttp@274fe449{r=2,c=false,a=IDLE,uri=-} handle enter
DEBUG [2017-12-14 21:27:04,770] qtp1140430871-53 - http://my-test-bucket.s3.amazonaws.com/?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1513391225&Signature=GEkjHl7OLsfH%2FgT8evi%2BaYtEo64%3D - org.eclipse.jetty.server.HttpChannelState HttpChannelState@65a6f2b0{s=IDLE i=true a=null} handling IDLE
DEBUG [2017-12-14 21:27:04,770] qtp1140430871-53 - http://my-test-bucket.s3.amazonaws.com/?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1513391225&Signature=GEkjHl7OLsfH%2FgT8evi%2BaYtEo64%3D - org.eclipse.jetty.server.HttpChannel HttpChannelOverHttp@274fe449{r=2,c=false,a=DISPATCHED,uri=/} action REQUEST_DISPATCH
DEBUG [2017-12-14 21:27:04,770] qtp1140430871-53 - http://my-test-bucket.s3.amazonaws.com/?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1513391225&Signature=GEkjHl7OLsfH%2FgT8evi%2BaYtEo64%3D - org.eclipse.jetty.server.Server REQUEST HEAD / on HttpChannelOverHttp@274fe449{r=2,c=false,a=DISPATCHED,uri=/}
INFO [2017-12-14 21:27:04,775] qtp1140430871-53 - http://my-test-bucket.s3.amazonaws.com/?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1513391225&Signature=GEkjHl7OLsfH%2FgT8evi%2BaYtEo64%3D - io.pithos.sig will throw because of failed signature!
DEBUG [2017-12-14 21:27:04,775] qtp1140430871-53 - http://my-test-bucket.s3.amazonaws.com/?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1513391225&Signature=GEkjHl7OLsfH%2FgT8evi%2BaYtEo64%3D - io.pithos.sig string-to-sign:  HEAD
```

My suspicions are that the issue has something to do with Regions, but I don't know exactly what.

**Comment by brutasse** [comment]
Hello,

Your logs only show requests to `s3.amazonaws.com` -- is your SDK correctly configured to hit Pithos instead of AWS?

**Comment by mark-draper** [comment]
Hi, thanks for the quick reply!

Those are the Pithos logs. I grabbed them from the command prompt window where I executed Pithos. I set the log level in the pithos.yaml to Trace - that's the only change to the pithos.yaml from the one on the pithos Quickstart.

This is how I configured the client in .NET:

AWSConfigsS3.UseSignatureVersion4 = false;
AmazonS3Config config = new AmazonS3Config();
config.ProxyHost = "127.0.0.1";
config.ProxyPort = 8080;
config.UseHttp = true;
config.SignatureVersion = "s3";
string accessKey = "AKIAIOSFODNN7EXAMPLE";
string secretKey = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";
Amazon.Runtime.BasicAWSCredentials creds = new Amazon.Runtime.BasicAWSCredentials(accessKey, secretKey);
IAmazonS3 s3Client = new AmazonS3Client(creds, config);

Like I said, it seems to connect and depending on bucketName I use, I can sometimes see a new record in the Cassandra database appear.

**Comment by brutasse** [comment]
Ah yes, thank you for the info.

In the first case you are in path-style access, whereas in the second it's a subdomain-style access. I suspect Pithos isn't able to extract the bucket correctly. This usually has to do with `options -> service-uri` in the pithos config. Which value did you set?

**Comment by mark-draper** [comment]
Hi!

All options in pithos.yaml are exactly as the example one found at http://pithos.io/quickstart.html:

## global options
## --------------
options:
  service-uri: 's3.example.com'
  reporting: true
  server-side-encryption: true
  multipart-upload: true
  masterkey-provisioning: true
  masterkey-access: true
  default-region: 'CH-GV1'

To give you a bit of background... our software system (which is already in production) has a Pithos service that uses this example pithos.yaml without any changes and there is another service that has a client coded using the Java SDK that uses it. I am working on a second client coded in .NET that will access the same Pithos service but will be using different buckets.

Since last week, I have been able to upload, download and delete files without issue as long as I choose a bucket name that works.

Thank you for your help,

Mark

**Comment by brutasse** [comment]
Right. So in your case, endpoints use the host 's3.amazonaws.com' which doesn't match 's3.example.com'. Setting service-uri to `s3.amazonaws.com` should fix your issue for all bucket names. Let me know!

**Comment by mark-draper** [comment]
That works, yes. I tried it and I can use all bucket names.

But I guess I was not clear - I cannot do that. I'm trying to connect to a running Pithos service that uses 's3.example.com' in the pithos.yaml. I need to be able to connect to this existing service using the .NET client, and I cannot figure out how to do that and make it work with all bucket names.

Thanks for your help!

**Comment by mark-draper** [comment]
Update:

I may be able to do this. I stopped the running pithos service that was original started with s3.example.com in pithos.yaml and replaced that with s3.amazonaws.com and restarted the service. I can use all bucket names now using my new .NET client and can access everything as well with the existing Java client with no changes.

If I run into any issues I'll post here, but for now, thanks for all the help!

**Comment by brutasse** [comment]
Perfect, that's what I meant with my previous comment. Glad it's all good now.
