### ISSUE TITLE
Support V4 signatures

### ISSUE THREAD

**Issue by pyr** [exoscale/pithos#52]

**Comment by damiencriado** [comment]
:+1:

**Comment by damiencriado** [comment]
Il y'a une date de prévu ?

**Comment by pyr** [comment]
Still no date planned, though this is the number one priority as far as pithos development is concerned now.

**Comment by TheKoon** [comment]
Any news ?

**Comment by phene** [comment]
:+1: I hope this gets worked on soon.

**Comment by FredericJacobs** [comment]
> though this is the number one priority as far as pithos development is concerned now.

Any updates?

**Comment by pyr** [comment]
Hi everyone, sorry for the lag. The only indication I can give is that there are plans to spend a good amount of time working out the necessary architectural changes before fall.

We're starting work to integrate additional external S3 compatibility test-suites as well to ensure we remain compatible.

**Comment by cybojanek** [comment]
If you do plan to add support, please also consider streaming support:
http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

**Comment by pozylon** [comment]
Hi guys, good to here that you're still working on this. I use preflight signing to have the client directly upload to an aws bucket. see here: https://github.com/CulturalMe/meteor-slingshot

This makes my application more scalable and helps saving bandwidth/cpu. I would love to migrate the block storage to exoscale as the application already runs on your platform.

**Comment by FredericJacobs** [comment]
[Minio](https://blog.minio.io/command-line-access-to-google-cloud-storage-35b5c6806aab) supports V4 signatures and seems to get more attention.
Thinking of spinning up an instance rather than have to deal with unmaintained Exoscale's storage.

**Comment by pyr** [comment]
Hi,

I am not sure where you are getting unmaintained from. We are lagging behind on features but spending time consolidating those we have.

Minio is single instance ATM, pithos is obviously not. 

We plan to use minio's s3 verify tool though to help with compliance.

On August 31, 2016 3:32:28 AM GMT+02:00, Frederic Jacobs <notifications@github.com> wrote:
>[Minio](https://blog.minio.io/command-line-access-to-google-cloud-storage-35b5c6806aab)
>supports V4 signatures and seems to get more attention.
>Thinking of spinning up an instance rather than have to deal with
>unmaintained Exoscale's storage.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/exoscale/pithos/issues/52#issuecomment-243632927

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pozylon** [comment]
Great, thank you pyr.

**Offtopic**: Do you have plans building a Swiss CDN service to cache static assets or does anybody know a provider? These were the services I was looking for when building our modern web apps hosted in Switzerland:

1. PaaS (docker-driver is perfect, no need for PaaS, check)
2. Block Storage (check)
3. CDN (Swisscom CDN?)
4. Something like Twilio (http://www.aspsms.ch?)
5. Stripe
6. Google Analytics
7. Mailchimp (could be https://mailtrain.org running as SaaS)
8. Log Management (current solution: self-hosted ELK stack, could be delivered as SaaS)

**Comment by FredericJacobs** [comment]
@pyr : Been more than a year that we were promised V4 signatures ... 
https://github.com/exoscale/pithos/issues/64#issuecomment-126283241

**Comment by pyr** [comment]
@FredericJacobs yes, as you might have noticed, the workforce on pithos is limited. behind the scene, most of the work is spent on the most pressing needs: reducing latency and improving blob storage efficiency, the v4 signature work has taken a back seat to this. it still will happen and i think solutions such as minio's s3verify will help a lot in the future.

**Comment by phene** [comment]
Lack of v4 signature support has become a major problem for my team. This is entirely incompatible with the aws-sdk Ruby library and many other aws-compatible libraries.

**Comment by pyr** [comment]
HI @phene,

As mentioned in the previous comment, work on improving storage efficiency is taking all the existing team's bandwidth.

I understand the frustration this may cause, we expect to have our performance work to be done in early 2017, which takes into account the need to adapt where signing plugs-in to the workflow to make V4 feasible. It might sound as though it's an easy change, but V4 breaks the request -> validation -> execution workflow which pithos implemented, since signatures may be per-chunk on the body.

I'll add that we would *of course* welcome a PR implementing it.

**Comment by pyr** [comment]
fixed in #2069
