### ISSUE TITLE
Using sos.exoscale.ch with Boto

### ISSUE THREAD

**Issue by FredericJacobs** [exoscale/pithos#62]
> boto
> Fully tested with the current API coverage.

The Pithos documentation claims to support Boto. I have however not been able to open a S3Connection to sos.exoscale.ch. Do you have a sample configuration of that works?

Thanks.

**Comment by llambiel** [comment]
Hi,

Host is sos.exo.io, not sos.exoscale.ch.

Sample code is available [here](https://github.com/llambiel/cloud-canary/blob/master/s3-canary.py)

Thanks

**Comment by FredericJacobs** [comment]
Sweet! :+1:
