### ISSUE TITLE
Pre-signed requests with Boto3

### ISSUE THREAD

**Issue by FredericJacobs** [exoscale/pithos#64]
I'm trying to generate pre-signed requests with Boto3 for use with Exoscale's SOS but no luck so far.

I'm currently generating the s3Client with the following code.

```python
s3Client = client("s3",    aws_access_key_id        = S3_ACCESS_KEY,
                                      aws_secret_access_key = S3_SECRET_KEY,
                                      endpoint_url                    = EXOSCALE_HOST_URL)
```

I've figured out that a lot of [`botocore`](https://github.com/boto/botocore) endpoints are "fixing" the host field by replacing it the host with an Amazon domain: https://github.com/boto/botocore/blob/develop/botocore/utils.py#L599 

In an attempt to fix that, I've added a non-valid region name so that the [`if`]( https://github.com/boto/botocore/blob/develop/botocore/utils.py#L630) condition never gets executed. I get the correct domain but the POST requests results in a 403.

Any help appreciated!

**Comment by FredericJacobs** [comment]
This would require #52

**Comment by FredericJacobs** [comment]
@pyr || @llambiel : Any clues?

**Comment by brutasse** [comment]
@FredericJacobs If you're interested I have a small authenticator for the `requests` library that is able to sign requests for Pithos, using signature v2:

```python
import base64
import hashlib
import hmac
import time

from datetime import datetime
from urllib.parse import urlparse, quote, urlencode

from requests.auth import AuthBase


class AwsV2Auth(AuthBase):
    def __init__(self, key, secret, presigned_ttl=3600):
        self.key = key
        self.secret = secret
        self.presigned_ttl = presigned_ttl

    def __call__(self, request):
        date = datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S +0000')
        request.headers['x-amz-date'] = date
        signature = self.sign(request.method, request.url, request.headers)
        request.headers['Authorization'] = 'AWS {0}:{1}'.format(self.key,
                                                                signature)
        return request

    def sign(self, method, url, headers, expires=None):
        parsed = urlparse(url)
        path = parsed.path
        sig_headers = sorted([[k.lower(), v]
                              for k, v in headers.items()
                              if k.lower().startswith('x-amz-')],
                             key=lambda i: i[0])
        sig_headers = "\n".join((
            ":".join((key, value))
            for key, value in sig_headers
        ))
        parts = [method,
                 headers.get('Content-MD5', ''),
                 headers.get('Content-Type', ''),
                 # date provided in x-amz-date if not from Expires
                 str(expires) if expires is not None else ""]
        if sig_headers:
            parts.append(sig_headers)
        parts.append(quote(path, safe='/$'))

        string_to_sign = "\n".join(parts)
        return base64.b64encode(hmac.new(
            self.secret.encode(),
            string_to_sign.encode(),
            digestmod=hashlib.sha1,
        ).digest()).decode()

    def pre_sign(self, url, method='GET', headers=None, expires=None):
        if expires is None:
            expires = int(time.time()) + self.presigned_ttl
        if headers is None:
            headers = {}
        sig = self.sign(method, url, headers, expires)
        qs = urlencode({'Expires': expires,
                        'Signature': sig,
                        'AWSAccessKeyId': self.key})
        return '{0}?{1}'.format(url, qs)
```

With this you can do `requests.get('https://pithos.example.com/my-bucket', auth=AwsV2Auth(key, secret))` to interact normally with the API or generate a pre-signed url:

```python
url = 'https://pithos.example.com/my-bucket/path/to/object'
auth = AwsV2Auth(key, secret)
signed_url = auth.pre_sign(url)
```

This is Python3 code so if you're using Python 2 you may have to change some imports and add 'utf-8' to some encode/decode calls.

**Comment by FredericJacobs** [comment]
Does that mean that V4 signatures are nowhere close?

**Comment by pyr** [comment]
@FredericJacobs not necessarily but I don't have a time-frame for them yet.

**Comment by pyr** [comment]
In the mean-time I will be closing this, since it is essentialy the same as #52

**Comment by FredericJacobs** [comment]
@pyr: We really have the need to have some reliable S3-like functionality in production by end of August. We would love to use Exoscale but it seems pretty difficult to use up-to-date libraries with Pithos.

We need to be able to configure buckets, CORS settings, and sign requests (preferably V4 all of this simply). 

It does appear that Boto3 is not supported and Boto2 doesn't support signing with V4. Can you provide an approximate time frame to know if we should switch storage provider or if it is likely that by the end of August you will have implemented the support for the new signatures. It would be preferable for us to deploy everything to production with a more maintainable codebase than what you're currently suggesting.

**Comment by pyr** [comment]
@FredericJacobs v4 signature work has already started. The exact timeframe is hard for me to make out though, since it has properties which impact the architecture of the software (request signing is now coupled with request payloads). From the looks of it, end of august is a reasonable target though, I just can't commit to it.

**Comment by FredericJacobs** [comment]
@pyr : Any updates to this?
