### ISSUE TITLE
is pithos itself fault tolerant?

### ISSUE THREAD

**Issue by ogg1e** [exoscale/pithos#66]
Can you run multiple instances of pithos against the same C* cluster? So if you have 3 nodes, you have pithos running on each node.  Or is that impossible at this point? 

If it's not possible, that would be a great feature to have and eliminate another SPOF.

**Comment by vincentbernat** [comment]
Pithos is stateless. You can run one instance on each node.

**Comment by ogg1e** [comment]
Perfect.
