### ISSUE TITLE
Doesn't work with s3fs-fuse and large jar files (40MB)

### ISSUE THREAD

**Issue by ogg1e** [exoscale/pithos#70]
If I use s3cmd to get/put jar files into pithos, it works.

But if I tried to use the latest s3fs-fuse (1.79) and fuse (2.9.3) to retrieve jar files in pithos, they seem to be corrupted and not usable. This happens even if I upload the jar with s3cmd or s3fs. 

Can't say for 100% that it's pithos though... smaller text files seem to be fine.

**Comment by vincentbernat** [comment]
Just a wild guess for a workaround: try with `-o nomultipart`.

**Comment by ogg1e** [comment]
That's for uploads though. I have this issue with downloads.

**Comment by numbat** [comment]
I've not use Fuse but see if there is an option to disable range requests for downloading. It sounds like you are encountering this issue:

https://github.com/exoscale/pithos/issues/57

**Comment by numbat** [comment]
Long shot - see if you can set this to 0 or 1:

parallel_count (default="5")

number of parallel request for downloading/uploading large objects. s3fs uploads large object(over 20MB) by multipart post request, and sends parallel requests. This option limits parallel request count which s3fs requests at once.

**Comment by ogg1e** [comment]
I think that fixed it. With this fstab string, it now seems to work:
```
s3fs#int-bucket /opt/buckets/int fuse _netdev,allow_other,use_path_request_style,url=http://10.6.71.202:8080,use_cache=/tmp,nonempty,nomultipart,parallel_count=1 0 0
```

So by adding nomultipart and parallel_count=1 initial tests worked. I'll do some more testing today, but it looks good so far. Thanks!

**Comment by ogg1e** [comment]
So that worked for a jar file that was 20MB, but now it fails for a tar.gz file that's around 125 MB.  It get so far extracting and throws this:
```
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

But if I use s3cmd exclusively, it's fine.

**Comment by ogg1e** [comment]
I works on smaller tar.gz files, so it's not the file type that's an issue. It just seems to be the size of the file.

I also tried it on a 200MB zip file and had the same results.

However, I found out something more interesting. If I upload the file with s3cmd, I can't use it with s3fs. If I upload with s3fs, I can use it with s3fs. So there's something different between s3cmd upload and s3fs upload.

**Comment by ogg1e** [comment]
I was wrong in my last comment. If I upload it via s3fs and then attempt to use the tar.gz file on the same server, I can extract it no problem. But if I go to another server that has that bucket mounted to a folder via s3fs, I get the same gzip error.

**Comment by pyr** [comment]
@ogg1e any chance that s3fs can let you debug the queries being sent so I have a shot at figuring out what is going on?

**Comment by retrack** [comment]
to my knowledge it is not advised to share an S3FS bucket mounted on several servers. There are no file locking, or referential integrity checks that you’d expect on a proper NFS type filesystem. If more than one instance is trying to update the same object at any given time then you run the risk of corrupting the data.

**Comment by ogg1e** [comment]
I abandoned using s3fs due to this issue.  I replaced it with s3cmd and an nginx proxy instead. However, I  enabled s3fs debugging and it didn't reveal much. Here's what I saw when I placed the file:
```
Feb 15 19:17:38 test01-1 s3fs: Body Text:
Feb 15 19:17:38 test01-1 s3fs: Body Text:
Feb 15 19:17:38 test01-1 s3fs: Body Text:
Feb 15 19:17:38 test01-1 s3fs: Body Text:
Feb 15 19:17:38 test01-1 s3fs: Body Text:
Feb 15 19:17:38 test01-1 s3fs: Body Text:
Feb 15 19:17:38 test01-1 s3fs: Body Text:
Feb 15 19:17:38 test01-1 s3fs: Body Text:
Feb 15 19:17:38 test01-1 s3fs: Body Text:
Feb 15 19:17:38 test01-1 s3fs: file locked(/spark-1.1.0.zip - /tmp/.int-bucket.stat/spark-1.1.0.zip)
Feb 15 19:17:38 test01-1 s3fs: file unlocked(/spark-1.1.0.zip)
Feb 15 19:18:02 test01-1 s3fs: file locked(/spark-1.1.0.zip - /tmp/.int-bucket.stat/spark-1.1.0.zip)
Feb 15 19:18:02 test01-1 s3fs: file unlocked(/spark-1.1.0.zip)
```

Here's what I see when I pull it down on another server and I'm unable to extract:

```
Feb 15 19:18:31 test01-2 s3fs: file locked(/spark-1.1.0.zip - /tmp/.int-bucket.stat/spark-1.1.0.zip)
Feb 15 19:18:31 test01-2 s3fs: file unlocked(/spark-1.1.0.zip)
Feb 15 19:18:50 test01-2 s3fs: file locked(/spark-1.1.0.zip - /tmp/.int-bucket.stat/spark-1.1.0.zip)
Feb 15 19:18:50 test01-2 s3fs: file unlocked(/spark-1.1.0.zip)
```
