### ISSUE TITLE
Question: How can I determine if install-schema has already been run?

### ISSUE THREAD

**Issue by phene** [exoscale/pithos#71]
I'm attempting to write my own chef recipe to use pithos and I'm struggling to determine when *not* to run `pithos -a install-schema`. Does `install-schema` create any files I could test for existence?

**Comment by pyr** [comment]
@phene install-schema does not create any files, the best way to make sure the schema has been converged is to fire up `cqlsh` on your cassandra cluster and ensure that `describe schema` on the clusters and verify that you see bucket, object, inode, inode_blocks, and block colum families.
