### ISSUE TITLE
s3n:// support

### ISSUE THREAD

**Issue by ogg1e** [exoscale/pithos#72]
Any chance pithos will support s3n:// requests in the future?

**Comment by pyr** [comment]
Hi @ogg1e, I'm not quite sure what is required to support them. Are you more familiar with the details of s3n ?

**Comment by ogg1e** [comment]
@pyr not really TBH. I just know that with running spark jobs on mesos, you can specify s3n:// and http:// URIs to resources. If pithos supported s3n:// requests, I could eliminate the need to proxy objects stored in pithos with nginx.

**Comment by pyr** [comment]
@ogg1e can you try s3n:// requests again and let me know how that goes (ideally with some logging :-))

**Comment by ogg1e** [comment]
@pyr I'm no longer with the same company, so I don't have a running environment with Pithos installed.

**Comment by pyr** [comment]
@ogg1e thanks anyway!
