### ISSUE TITLE
CORS Headers from Exoscale Dashboard panel not served?

### ISSUE THREAD

**Issue by FredericJacobs** [exoscale/pithos#74]
I have set the following debugging configuration up on Exoscale and also tried other Origin settings
```xml
<?xml version="1.0" ?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
  </CORSRule>
</CORSConfiguration>

```

but I keep getting the following CORS issue on my browser. It does appear that the CORS headers are not served?

<img width="822" alt="screen shot 2015-08-18 at 18 14 54" src="https://cloud.githubusercontent.com/assets/400296/9335642/7f8eb9cc-45d5-11e5-9257-aa32047ca072.png">

**Comment by brutasse** [comment]
The CORS spec does not allow wildcards in allowed headers. They must be declared explicitly. Can you try listing them in multiple `AllowedHeader` blocks?

**Comment by FredericJacobs** [comment]
I tried with 

```
    <AllowedHeader>Authorization</AllowedHeader>
    <AllowedHeader>Content-Type</AllowedHeader>
```

But that didn't help.

**Comment by FredericJacobs** [comment]
Safari says `Failed to load resource: Origin http://{my_domain}.com is not allowed by Access-Control-Allow-Origin.` even though I tried wildcard and specifying domain.

**Comment by brutasse** [comment]
@FredericJacobs Chrome should be able to give you the response body when it says `The response had HTTP status code 403`. Could you provide the exact error message in the body?

**Comment by FredericJacobs** [comment]
No, you don't get a response because it's I assume a browser-generated 403 because the pre-flight headers are incorrect.

<img width="1440" alt="screen shot 2015-08-25 at 20 22 36" src="https://cloud.githubusercontent.com/assets/400296/9475558/b11a7688-4b67-11e5-9d76-5f9f10cb521b.png">

**Comment by FredericJacobs** [comment]
Maybe a nginx issue on sos.exoscale.io?

**Comment by brutasse** [comment]
It's not a browser 403, it's Pithos returning a 403 to your preflight request. A fix is on its way, it shouldn't be too long.

**Comment by brutasse** [comment]
Fixed in https://github.com/exoscale/pithos/commit/ec2cf177a5200b853fe1637e4ebca1c473b2603b

**Comment by FredericJacobs** [comment]
I assume that fixed it for the `OPTIONS` call but now the `PUT` request gets a 403.

**Comment by brutasse** [comment]
What is the body of the response for the PUT request? 403 could be CORS-related but also a signature issue.
