### ISSUE TITLE
Log4j integration not working?

### ISSUE THREAD

**Issue by phene** [exoscale/pithos#82]
I have been trying to get log4j configured with pithos and I cannot get it to log anything to a file. Based on examples from pithos and cassandra, I am using this:

```
log4j.rootLogger=DEBUG, stdout, F

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%p [%d] %t - %c - %m%n

log4j.appender.F=org.apache.log4j.FileAppender
log4j.appender.F.File=/var/log/pithos/system.log
log4j.appender.F.layout=org.apache.log4j.PatternLayout
log4j.appender.F.layout.ConversionPattern=%p [%d] %t - %c - %m%n

log4j.logger.io.pithos=DEBUG
```

The pithos config was updated to include:

```yaml
logging:
  external: true
```

For some reason, `/var/log/pithos/system.log` is never written to, though it does appear to be touched whenever pithos is restarted. Any ideas?

**Comment by pyr** [comment]
Hi @thene,

the log4j examples are remnant of previous days. pithos now relies on logback for logging. if you want to bypass internal log configuration, you may set external to true as you did and provide a logback.xml file.

I'll make a note of updating docs for this.

**Comment by phene** [comment]
@pyr Is there an additional argument I need to provide the pithos binary for it to become aware of the logback.xml, or can I just put it in the same folder as my pithos configuration?

**Comment by phene** [comment]
Where is this change to the logging infrastructure? [This indicates](https://github.com/exoscale/pithos/blob/master/src/io/pithos/config.clj#L57) to me that log4j is still in use.

**Comment by pyr** [comment]
This is due to relying on a recent version of unilog which switched from log4j to logback

**Comment by phene** [comment]
Are we looking at the same code? There's no mention of unilog or logback in the pithos source tree, but there are still mentions of log4j. Where is this dependency specified?

**Comment by pyr** [comment]
It's implicit from project.clj

On April 8, 2016 7:16:37 PM CEST, Geoffrey Hichborn <notifications@github.com> wrote:
>Are we looking at the same code? There's no mention of unilog or
>logback in the pithos source tree, but there are still mentions of
>log4j. Where is this dependency specified?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/exoscale/pithos/issues/82#issuecomment-207522268

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
