### ISSUE TITLE
Incompatible with Apache Camel S3 component

### ISSUE THREAD

**Issue by pvalsecc** [exoscale/pithos#88]
At startup a camel S3 consumer does that:
https://github.com/apache/camel/blob/master/components/camel-aws/src/main/java/org/apache/camel/component/aws/s3/S3Endpoint.java#L115

Here is the line:
```
s3Client.listObjects(new ListObjectsRequest(bucketName, null, null, null, 0));
```

The real S3 service returns 200 if the bucket exists and and error if it doesn't.

Pithos is another story:
```
Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: '' LIMIT 0;"], :values nil} (Service: null; Status Code: 500; Error Code: Unknown; Request ID: e098f9c0-513b-4675-8061-f748f6752749), S3 Extended Request ID: e098f9c0-513b-4675-8061-f748f6752749
```

I tried to change the java code to (put 1 instead of 0 for the maxKeys parameter):
```
s3Client.listObjects(new ListObjectsRequest(bucketName, null, null, null, 1));
```

And everybody is happy.

Can you, please, make Pithos support maxKeys=0?

I'm using whatever version/config of Pithos that is currently active at Exoscale.

**Comment by pyr** [comment]
Hi @pvalsecc,

Thanks for pointing this out. Will take care of it shortly.

**Comment by pyr** [comment]
Hi, this is now fixed in master, a release will be published shortly.

**Comment by pvalsecc** [comment]
By "published" do you mean "installed on the Exoscale production servers"?

**Comment by pyr** [comment]
@pvalsecc but published, I mean released here on github as pithos 0.7. 6. As a side-effect, it will be deployed shortly on Exoscale as well.

**Comment by pyr** [comment]
@pvalsecc it's now deployed on Exoscale.

**Comment by pvalsecc** [comment]
Thanks @pyr, I've tested without my patch in Camel and it works fine, now.
