### ISSUE TITLE
Cassandra partition value limit

### ISSUE THREAD

**Issue by dylanwilder** [exoscale/pithos#90]
Cassandra currently has a limitation of ~2 billion cell values in a given row partition.  You are currently using bucket as a partition key and object path as the clustering key (to preserve sorted order. I've seen this mentioned in a few places so correct me if i'm wrong). Can I ask how you plan to scale past 100s of millions of objects per bucket? S3 boasts no limit on the number of objects in a bucket.

**Comment by pyr** [comment]
Hi @dylanwilder,

You're right that this is the current design. There are no immediate plans to support this use-case. An alternate metastore relying on the recent SASI indices would be an option there, but I'll say we cross that bridge once we get to it :-)
