### ISSUE TITLE
missing mapping for :delete-bucket-acl method?

### ISSUE THREAD

**Issue by mltest1234** [exoscale/pithos#92]
When i try to execute DELETE Bucket ACL i receive 400 response code. In logs i can see:
DEBUG [2016-05-10 19:17:59,892] qtp705126000-59 - io.pithos.operations - handling operation:  :delete-bucket-acl
However in  io.pithos.operations.clj file i can not see mapping for :delete-bucket-acl (lines 693-810).
E.g I can find mapping for method :delete-bucket-cors (line 732)
Am i missing something or mapping for :delete-bucket-acl method is missing?

**Comment by pyr** [comment]
Hi!

There is no delete bucket ACL operation in the S3 protocol.
You're expected to use the put bucket ACL operation.

**Comment by mltest1234** [comment]
Hi!
But you can find description of "DELETE Bucket ACL" (together with sample request) in your documentation (http://pithos.io/api.html -> S3 API). If there is no such method, you should update a documentation

**Comment by mltest1234** [comment]
Hi,
There is no answer to my last comment. If someone (e.g @pyr) watches this issue, please comment my last comment. If not I will add a new issue:-)

**Comment by pyr** [comment]
@mltest1234 indeed, I'll update the docs, thanks for pointing it out!
