### ISSUE TITLE
pithos 0.7.4. What is expected body content for "POST Object upload" method

### ISSUE THREAD

**Issue by mltest1234** [exoscale/pithos#93]
Hi,
I try to implement "POST Object upload" method. On the page http://pithos.io/api.html -> "POST Object upload" there is no information, what (there is no information that anything should be sent) should be sent as body for request. There is only sample for response. But if i do send nothing in body i receive exception like below. What should I send as body for "POST Object upload" request? (from lines 618-625 in operations.clj file I suspect that body is xml and contains multipart, part and etag tags. But I can be wrong. An example would be very helpful)

<?xml version="1.0" encoding="UTF-8"?><Error><Code>Unknown</Code><Message>clojure.lang.ExceptionInfo: invalid XML in body {:type :invalid-multipart-xml, :original #error { :cause "ParseError at [row,col]:[1,1]\nMessage: Vorzeitiges Dateiende." :via [{:type javax.xml.stream.XMLStreamException   :message "ParseError at [row,col]:[1,1]\nMessage: Vorzeitiges Dateiende."   :at [com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl next nil -1]}] :trace [[com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl next nil -1]  [clojure.data.xml$pull_seq$fn__9655 invoke "xml.clj" 287]  [clojure.lang.LazySeq sval "LazySeq.java" 40]  [clojure.lang.LazySeq seq "LazySeq.java" 49]  [clojure.lang.RT seq "RT.java" 507]  [clojure.core$seq__4126 invoke "core.clj" 135]  [clojure.data.xml$seq_tree$fn__9563 invoke "xml.clj" 178]  [clojure.lang.LazySeq sval "LazySeq.java" 40]  [clojure.lang.LazySeq seq "LazySeq.java" 49]  [clojure.lang.LazySeq first "LazySeq.java" 71]  [clojure.lang.RT first "RT.java" 653]  [clojure.core$first__4108 invoke "core.clj" 55]  [clojure.core$ffirst__4118 invoke "core.clj" 103]  [clojure.data.xml$event_tree invoke "xml.clj" 194]  [clojure.data.xml$parse doInvoke "xml.clj" 346]  [clojure.lang.RestFn invoke "RestFn.java" 410]  [clojure.lang.AFn applyToHelper "AFn.java" 154]  [clojure.lang.RestFn applyTo "RestFn.java" 132]  [clojure.core$apply invoke "core.clj" 630]  [clojure.data.xml$parse_str doInvoke "xml.clj" 354]  [clojure.lang.RestFn invoke "RestFn.java" 410]  [io.pithos.xml$xml__GT_multipart invoke "xml.clj" 35]  [io.pithos.operations$complete_upload invoke "operations.clj" 618]  [io.pithos.operations$dispatch$fn__10445 invoke "operations.clj" 870]  [io.pithos.operations$dispatch invoke "operations.clj" 866]  [io.pithos.api$executor$fn__12399 invoke "api.clj" 21]  [qbits.jet.server$make_handler$fn__8819 invoke "server.clj" 70]  [qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]  [org.eclipse.jetty.server.handler.HandlerList handle "HandlerList.java" 52]  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 97]  [org.eclipse.jetty.server.Server handle "Server.java" 497]  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 310]  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 257]  [org.eclipse.jetty.io.AbstractConnection$2 run "AbstractConnection.java" 540]  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 635]  [org.eclipse.jetty.util.thread.QueuedThreadPool$3 run "QueuedThreadPool.java" 555]  [java.lang.Thread run nil -1]]}, :status-code 400}</Message><RequestId>acb5d5f0-1d31-4d25-9815-49eec95fc7e9</RequestId><HostId>acb5d5f0-1d31-4d25-9815-49eec95fc7e9</HostId></Error>

**Comment by pyr** [comment]
Hi, for post object uploads, you can refer to this documentation: http://docs.aws.amazon.com/AmazonS3/latest/dev/HTTPPOSTForms.html
